#!/bin/sh

# TODO: atomic builds.
# TODO: use GNU parallel?
# TODO: remove duplicate code.

if [ -d dist ]; then
    rm -rf dist/*
    cp -r static/* dist
else
    git worktree add dist master
    exec "$0"
fi

(
    cd src
    # TODO: don't require assets dir hack.
    for i in $(find . -name 'assets' -type d); do
        rsync -rR "$i" ../dist/
    done
)

dest () { echo "$1" | sed 's/^src\/\(.*\)\..*\?$/dist\/\1.html/'; }
gen () { cat | ./gen 'template.html' "$1"; }

for page in $(find src/ -type f -name '*.html'); do
    {
        dest="$(dest "$page")"
        mkdir -p "$(dirname "$dest")"
        gen "$dest" < "$page"
        echo "$page --> $dest"
    } &
done

for page in $(find src/ -type f -name '*.md'); do
    {
        dest="$(dest "$page")"
        mkdir -p "$(dirname "$dest")"
        pandoc -f gfm -t html "$page" | gen "$dest"
        echo "$page --> $dest"
    } &
done

wait
