#!/bin/sh

# Place deployable files in the `dist/` dir ready for deployment.

if [ ! -d 'dist' ]; then
    git worktree add dist master
else
    rm -r dist/*
fi

files() {
    {
        find . -name '*.html' -type f

        for dir in `find . -name 'assets' -type d`
        do
            find "$dir" -name '*' -type f
        done

        echo "favicon.ico"
        echo "robots.txt"
        echo "LICENCE"
        echo "CNAME"

    } | sed 's/^\.\///'
}

for i in `files`; do
    # TODO: can rsync operate on directories?
    rsync -R "$i" dist/
done

# TODO: git diff and ask to commit (give auto-message)?
